unformated_results = [
    {
        "id": "football/2025/apr/09/maxi-oyedele-legia-warsaw-chelsea-conference-league-manchester-united",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2025-04-09T09:14:23Z",
        "webTitle": "Maxi Oyedele: from Manchester United outcast to ‘dream’ tie against Chelsea ",
        "webUrl": "https://www.theguardian.com/football/2025/apr/09/maxi-oyedele-legia-warsaw-chelsea-conference-league-manchester-united",
        "apiUrl": "https://content.guardianapis.com/football/2025/apr/09/maxi-oyedele-legia-warsaw-chelsea-conference-league-manchester-united",
        "fields": {
            "bodyText": "Fourteen months ago, Maxi Oyedele was experiencing the lowest moment of a burgeoning career, being substituted after coming off the bench for a team destined for relegation from League Two. Now he is preparing for a European quarter-final with Legia Warsaw against one of the biggest clubs on the continent. Forest Green feels a world away. When any teenager is loaned by Manchester United to a lower-league club, the aim is for them to gain experience that can help them progress. In theory, this is done through positive performances and playing against senior professionals, allowing a youngster to learn the tricks of the trade. Sometimes, however, a setback is the best learning curve. It has helped the midfielder earn full international honours, the Conference League battle with Chelsea in Warsaw on Thursday and a Polish Cup final next month. “I would put that down as one of my most valuable experiences, going to Forest Green and it not working out the way I wanted it to,” says Oyedele, who returned to United after four substitute appearances in League Two. “The way I had to come back to the club and be back in the under-21 squad and be training in and out with the first team … that whole period was extremely, extremely tough. Whatever problems I face I know what it’s like to be at the lowest point. It’s only made me stronger.” A move to eastern Europe may not sound like an obvious move for someone who was brought up in Salford and joined United aged six, but Oyedele has a Polish mother and a Nigerian father. Oyedele regularly visited his mother’s homeland as a child, learning the language to interact with his grandmother, and started representing Poland as a teenager. Legia came calling in the summer, offering a homecoming of sorts when it became clear he was not in Erik ten Hag’s plans. “It’s just funny for my mum because she left Poland to come to England and make a life; I left England to go to Poland to start my journey,” says Oyedele. “Legia was the biggest opportunity. I don’t even think I realised how big of an opportunity it was when I heard about it. I felt like this was the opportunity to play in Europe, the biggest team in Poland. It’s my nationality, so it’s close to the national team. It’s always a risk to leave it, but it just seemed like the best choice” The deal was completed in late August and within a couple of months Oyedele had ticked off a top-flight, European and full international debut. The central midfielder won two caps for Poland last year against Portugal, where he swapped shirts with his former club captain Bruno Fernandes, and Croatia. “I always thought I would love to leave and start a new journey abroad,” he says. “I couldn’t afford to waste another year playing academy football. I could have stayed in England and continued my journey and who knows what would have happened. I might have not been anywhere near and now I’m about to play Chelsea.” A cacophony of noise and pyrotechnics will be used at Legia’s stadium to create an intimidating atmosphere in the hope of putting Chelsea on the back foot in a tie they are heavy favourites to win. The eclectic nature of the Conference League means Legia, fifth in Poland’s top division, have defeated the Welsh Premier league side Caernarfon and Real Betis on their way to this stage. “I can’t even begin to describe the Legia fans,” says Oyedele. “It’s one of the best things I’ve seen. I go to the stadium and I’m looking around thinking: ‘Wow. It’s unbelievable. I can’t wait to play, in front of these fans. My debut, the fans were crazy. “You just rise, it absolutely lifts you up. And then walking out they had the tifo and I was thinking: ‘This is why I play football.’ I’ve never seen anything like it for me” Legia went through three playoff rounds starting in July to reach the Conference League group stage. It has been a circuitous route to a first European quarter-final since a defeat by Panathinaikos in the Champions League 29 years ago. Anticipation has been building since they beat Molde in the last round. “When I first joined, I watched us in the [Conference] League and thought I would love to play Chelsea,” Oyedele says. “This was months ago, in August. For us to get to this point, to have the opportunity to play such a big game … it was this dream. This is everybody wanted and when the game finished [against Molde], we had done it. “Now all that dream stuff is gone – it’s reality. We know that it’s Chelsea, so it’s going to be tough, but it’s a case of why not? I bet everybody thought we were going to lose to Real Betis and look what we did then.”"
        },
        "tags": [
            {
                "id": "football/legiawarsaw",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Legia Warsaw",
                "webUrl": "https://www.theguardian.com/football/legiawarsaw",
                "apiUrl": "https://content.guardianapis.com/football/legiawarsaw",
                "references": [],
            },
            {
                "id": "football/europa-conference-league",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Europa Conference League",
                "webUrl": "https://www.theguardian.com/football/europa-conference-league",
                "apiUrl": "https://content.guardianapis.com/football/europa-conference-league",
                "references": [],
            },
            {
                "id": "football/chelsea",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Chelsea",
                "webUrl": "https://www.theguardian.com/football/chelsea",
                "apiUrl": "https://content.guardianapis.com/football/chelsea",
                "references": [],
                "description": "Read the latest Chelsea news, transfer rumours, match reports, fixtures and live scores from the Guardian",
            },
            {
                "id": "football/football",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Football",
                "webUrl": "https://www.theguardian.com/football/football",
                "apiUrl": "https://content.guardianapis.com/football/football",
                "references": [],
            },
            {
                "id": "sport/sport",
                "type": "keyword",
                "sectionId": "sport",
                "sectionName": "Sport",
                "webTitle": "Sport",
                "webUrl": "https://www.theguardian.com/sport/sport",
                "apiUrl": "https://content.guardianapis.com/sport/sport",
                "references": [],
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/sport",
        "pillarName": "Sport",
    },
    {
        "id": "football/2025/apr/08/aston-villa-marco-asensio-paris-saint-germain-psg-champions-league",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2025-04-08T20:00:21Z",
        "webTitle": "Asensio makes PSG return with task of knocking parent club out of Europe",
        "webUrl": "https://www.theguardian.com/football/2025/apr/08/aston-villa-marco-asensio-paris-saint-germain-psg-champions-league",
        "apiUrl": "https://content.guardianapis.com/football/2025/apr/08/aston-villa-marco-asensio-paris-saint-germain-psg-champions-league",
        "fields": {
            "bodyText": "Presumably some time between making another play for Marco Asensio and the Paris Saint-Germain forward pitching up on loan in February, Unai Emery, or at least Aston Villa’s administrative staff, sifted through the small print of Uefa’s regulations in case this very scenario presented itself. Less than three months after replacing Kvara Kvaratskhelia at Parc des Princes in a Ligue 1 draw against Reims, Asensio faces the unusual but not unprecedented challenge of trying to knock his parent club out of the Champions League, the competition PSG crave so badly. Villa were on the other end of this peculiarity in October, though the stakes were nowhere near as high. When Bologna came to Birmingham, they arrived with a Villa player in their ranks. With Villa leading 2-0, coasting towards a victory that maintained their 100% start to the league phase, Samuel Iling-Junior entered late on to gentle applause from all sides. It was the 21-year-old’s first appearance at Villa Park – albeit for the visitors – and it could prove his last given Iling-Junior, who signed from Juventus last summer as part of the package that saw Douglas Luiz depart, joined Middlesbrough on loan in February. “It is probably a strange one because you can never predict that you’re going to face your own team,” says the Villa midfielder Youri Tielemans. “He has been brilliant since he came in, he is working hard on the pitch, making efforts for the team defensively, and offensively you can see his class when he touches the ball. I remember his first cameo at Villa Park [against Tottenham in the FA Cup] and it was just brilliant, he just glided [past] some of the midfielders.” There is the sense Asensio is just getting started. Villa have been building his fitness, resisting the temptation to showcase their shiny new toy at every opportunity. It has been a similar story with Marcus Rashford, who joined on loan from Manchester United. Here is an appetite to construct the perfect narrative arc around Rashford but Asensio has made a bigger splash. The 29-year-old has scored eight goals in 11 matches, eclipsing his tally of seven for PSG in double-quick time. Asensio has started five games for Villa, three in the Premier League, two in the FA Cup, in which Villa face Crystal Palace in the semi-finals towards the end of a busy month. To tee up this quarter-final, he scored three goals across two legs against Club Brugge. Villa won the European Cup in 1982 but this represents new territory for the club in the modern era. Asensio, meanwhile, is au fait with these kinds of matches and the grandest of stages: he is a three-time Champions League winner with Real Madrid. Villa have been impressed with his humility and character off the pitch. On it Asensio has shown a willingness to get his hands dirty, typified by his sliding challenge to deny Elliot Anderson a clean shot as Nottingham Forest pushed for an equaliser at the weekend when Villa were on the ropes. “No big egos,” Villa’s captain, John McGinn, said. “When you look at him you don’t think he’s a hard worker,” Tielemans says, “because he’s more of a ball player, but off the ball he does his job really well … I think the system suits him to play as a No 10 off the striker and for him to be ‘free’ off the striker.” How did Asensio get here? Emery tried to bring in Asensio in previous windows but it was always a complex – and expensive – deal. Villa’s manager drove his signing, aware his PSG counterpart, Luis Enrique, was not quite so enamoured. Enrique questioned Asensio’s attitude in training and commitment to trigger his team’s press in victory against Toulouse in November. Until then, he had played three of PSG’s four Champions League matches and 10 of their 12 league matches. Then Asensio voiced his surprise at the criticism given PSG had won comfortably and was benched a few days later against Bayern Munich. He totalled another 25 minutes before being allowed to depart. “When he has the ball, [he] is a top player,” Luis Enrique said ominously before that episode played out publicly. Villa do not have an option to sign the Spaniard and nor does he have a release clause in his PSG contract, which runs until 2026. Recently McGinn poked fun at an old social media post in which he declared his love for Asensio. On the night Asensio zipped a left-foot peach into the top corner to help Madrid past Barcelona to win the Supercopa de España, McGinn, then of Hibernian, posted on Twitter: “Asensio” and an emoji with a smiling face and heart-eyes. Asensio replied last week, posting a photo of the pair celebrating and the word: “Captain.” Asensio is symbolic of Villa’s rise under Emery. A player who appeared a fantasy target to those behind the scenes the summer after Emery averted the threat of relegation in 2022-23 evolved into a distinct possibility. Monchi, Villa’s sporting director, has been tasked with exploring a permanent deal. “He came to the [2022] World Cup with me and was very important, and he was important for us last season and at the start of this season,” Luis Enrique said on Tuesday. Could Asensio emulate those who have scored against their parent clubs in this competition? Patrick Roberts earned Celtic a point at the Etihad Stadium while a Manchester City player in 2016, though the game was a dead rubber. Fernando Morientes scored for Monaco to knock out Madrid in 2004 and Philippe Coutinho scored twice for Bayern in their 8-2 rout of Barcelona in 2020. James Rodríguez and Kingsley Coman scored against Real and Juventus respectively. If Asensio is burning with a point to prove, then so is Emery, who spent two years at PSG. His brief was to win the Champions League. He won Ligue 1 and two Coupes de France but in Paris they remember La Remontada, Barcelona’s 6-1 second-leg comeback which sent PSG packing from the last 16 of this competition in 2017, when McGinn was drooling over Asensio. Now, Emery has the player he has always pined for and Villa are in a place they could only dream of when he walked through the door."
        },
        "tags": [
            {
                "id": "football/aston-villa",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Aston Villa",
                "webUrl": "https://www.theguardian.com/football/aston-villa",
                "apiUrl": "https://content.guardianapis.com/football/aston-villa",
                "references": [],
            },
            {
                "id": "football/parisstgermain",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Paris Saint-Germain",
                "webUrl": "https://www.theguardian.com/football/parisstgermain",
                "apiUrl": "https://content.guardianapis.com/football/parisstgermain",
                "references": [],
            },
            {
                "id": "football/championsleague",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Champions League",
                "webUrl": "https://www.theguardian.com/football/championsleague",
                "apiUrl": "https://content.guardianapis.com/football/championsleague",
                "references": [],
            },
            {
                "id": "football/europeanfootball",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "European club football",
                "webUrl": "https://www.theguardian.com/football/europeanfootball",
                "apiUrl": "https://content.guardianapis.com/football/europeanfootball",
                "references": [],
            },
            {
                "id": "football/football",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Football",
                "webUrl": "https://www.theguardian.com/football/football",
                "apiUrl": "https://content.guardianapis.com/football/football",
                "references": [],
            },
            {
                "id": "sport/sport",
                "type": "keyword",
                "sectionId": "sport",
                "sectionName": "Sport",
                "webTitle": "Sport",
                "webUrl": "https://www.theguardian.com/sport/sport",
                "apiUrl": "https://content.guardianapis.com/sport/sport",
                "references": [],
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/sport",
        "pillarName": "Sport",
    },
    {
        "id": "us-news/2025/apr/08/trump-crypto-doj",
        "type": "article",
        "sectionId": "us-news",
        "sectionName": "US news",
        "webPublicationDate": "2025-04-08T16:17:31Z",
        "webTitle": "Trump’s justice department to disband unit investigating crypto fraud",
        "webUrl": "https://www.theguardian.com/us-news/2025/apr/08/trump-crypto-doj",
        "apiUrl": "https://content.guardianapis.com/us-news/2025/apr/08/trump-crypto-doj",
        "fields": {
            "bodyText": "The US justice department is disbanding a unit that was dedicated to investigating cryptocurrency-related fraud as Donald Trump’s presidential administration loosens oversight in the digital assets sector. In a four-page memo sent to justice department employees on Monday evening, the deputy attorney general, Todd Blanche, said that its national cryptocurrency enforcement team (NCET) “shall be disbanded effective immediately”. The memo from Blanche, who previously represented the president in the 2024 criminal trial that led to Trump’s conviction on 34 felony charges of falsifying business records, said that “the digital assets industry is critical to the nation’s economic development and innovation”. “The department of justice is not a digital assets regulator,” Blanche said. He then went on to criticize Trump’s presidential predecessor Joe Biden, saying: “However, the prior administration used the justice department to pursue a reckless strategy of regulation by prosecution.” The justice department will no longer pursue litigation or enforcement actions that have “the effect of superimposing regulatory frameworks on digital assets while President Trump’s actual regulators do this work outside the punitive criminal justice framework”, Blanche wrote. Rather, Blanche said, the department’s “investigations and prosecutions involving digital assets shall focus on prosecuting individuals who victimize digital asset investors, or those who use digital assets in furtherance of criminal offenses such as terrorism, narcotics and human trafficking, organized crime, hacking, and cartel and gang financing”. The decision to dissolve NCET, Blanche wrote, was part of the justice department’s efforts to comply with an executive order signed by Trump at the start of his second presidency in January. The executive order calls for the government to protect and promote “the ability of individual citizens and private-sector entities alike to access and use for lawful purposes open public blockchain networks without persecution”, among other objectives. Justice department officials, Blanche wrote, “will no longer target virtual currency exchanges, mixing and tumbling services, and offline wallets for the acts of their end users or unwitting violations of regulations”, among other instructions. Ongoing investigations that are “inconsistent” with this new policy “should be closed”, Blanche added. A justice department spokesperson did not immediately respond to a request for comment from the Guardian on Tuesday. According to the justice department’s website, NCET was established under Biden to “address the challenge posed by the criminal misuse of cryptocurrencies and digital assets”. Composed of attorneys with expertise in cryptocurrency, cybercrime and money laundering, the team was tasked with spearheading several high-profile crypto-related cases. The decision to disband the unit comes as Trump has expressed a desire to make the US the “crypto capital of the planet”. And he has advocated for easing regulations on the digital asset industry while also adopting pro-crypto policies. During his campaign for the White House last year, Trump wooed crypto companies to contribute to his campaign and to support his candidacy. Last autumn, it was announced that Trump and his sons were helping launch a new crypto venture called World Liberty Financial. And ahead of his inauguration, Trump launched a crypto token. According to Reuters, the Trump family has a claim on 75% of the net revenues from token sales by World Liberty Financial. Trump in March signed an executive order creating a strategic reserve of cryptocurrency for the US. And that same week, he hosted leaders from the crypto industry to the White House for a round-table discussion."
        },
        "tags": [
            {
                "id": "us-news/trump-administration",
                "type": "keyword",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webTitle": "Trump administration",
                "webUrl": "https://www.theguardian.com/us-news/trump-administration",
                "apiUrl": "https://content.guardianapis.com/us-news/trump-administration",
                "references": [],
                "description": "\u003cp\u003eNews about the Donald Trump White House administration, including comment and features from the Guardian\u003c/p\u003e",
            },
            {
                "id": "technology/cryptocurrencies",
                "type": "keyword",
                "sectionId": "technology",
                "sectionName": "Technology",
                "webTitle": "Cryptocurrencies",
                "webUrl": "https://www.theguardian.com/technology/cryptocurrencies",
                "apiUrl": "https://content.guardianapis.com/technology/cryptocurrencies",
                "references": [],
            },
            {
                "id": "us-news/us-news",
                "type": "keyword",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webTitle": "US news",
                "webUrl": "https://www.theguardian.com/us-news/us-news",
                "apiUrl": "https://content.guardianapis.com/us-news/us-news",
                "references": [],
            },
            {
                "id": "us-news/us-politics",
                "type": "keyword",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webTitle": "US politics",
                "webUrl": "https://www.theguardian.com/us-news/us-politics",
                "apiUrl": "https://content.guardianapis.com/us-news/us-politics",
                "references": [],
            },
            {
                "id": "us-news/donaldtrump",
                "type": "keyword",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webTitle": "Donald Trump",
                "webUrl": "https://www.theguardian.com/us-news/donaldtrump",
                "apiUrl": "https://content.guardianapis.com/us-news/donaldtrump",
                "references": [],
                "description": "\u003cp\u003eNews about Donald Trump, the 45th and 47th US president, including comment and features from the Guardian\u003c/p\u003e",
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/news",
        "pillarName": "News",
    },
    {
        "id": "football/2025/apr/08/leicester-city-football-daily-newsletter",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2025-04-08T15:11:33Z",
        "webTitle": "Football Daily | Leicester City and a sorry run of results that takes us back to 1977",
        "webUrl": "https://www.theguardian.com/football/2025/apr/08/leicester-city-football-daily-newsletter",
        "apiUrl": "https://content.guardianapis.com/football/2025/apr/08/leicester-city-football-daily-newsletter",
        "fields": {
            "bodyText": "RUUD AWAKENING Back in early November, Manchester United had sacked Erik ten Hag but were waiting for his permanent replacement, Ruben Amorim, to fly in from Portugal. In stepped Ruud van Nistelrooy, a club legend with a promising managerial pedigree, to deliver some interim magic. It worked surprisingly well: while Amorim was clearing his desk at Sporting, Van Nistelrooy went unbeaten in four home games across three competitions. In a further twist, Ruud’s reward for bringing a few feelgood vibes to the husk of Old Trafford was a one-way ticket through Carrington’s overcrowded door marked Do One. An important caveat for Ruud’s unbeaten run is that half of the games were against Leicester, who were beaten 5-2 in Milk Cup by United and 3-0 in the Premier League. It contributed to the departure of Steve Cooper, who had kept the Foxes above water but turned fans off with his conservative football and whiff of Nottingham Forest. But who to replace him? Perhaps a dashing Dutchman seen wandering towards Manchester airport. If Van Nistelrooy could beat this Leicester side so comprehensively, not once but twice, he must be good. Leicester’s new manager started off well with four points from two home games, but a trip to Newcastle in mid-December delivered a 4-0 defeat. That began a run of seven straight league losses, home fans quickly turning on Po’ Ruud as Leicester crashed into the bottom three. The Foxes enjoyed a b@ntorious win at Tottenham but Bilal El Khannous’ winner that day (26 January) was their last Premier League goal. It’s now April, with Leicester since racking up eight scoreless league defeats in a row, conceding 21 goals in the process. Newcastle started the slide towards the trapdoor and may have bolted it shut on Monday, winning 3-0 in a contest with all the intensity of a Sunday afternoon post-roast kickabout. Despite earning an early corner, Leicester still managed to go behind after two minutes, before Fabian Schär showed the Baller League a thing or two with a long-range crossbar assist for Jacob Murphy, who benefited as the entire home defence simply stood and watched on. So, while Amorim gets a natty retro hoodie to wear on the touchline (Big Sir Jim knocking 20% off as a goodwill gesture) and a soft-rock inspired terrace chant, all Po’ Ruud has are unwanted records – the longest run of league defeats without scoring since 1977, zero home league goals in five months. After Monday’s mismatch, Van Nistelrooy appeared ready to walk before, like Ivan Juric at Southampton, he is pushed out of the exit door when relegation is confirmed. “The most important thing is the club and these players,” Ruud muttered when asked about his future, before zipping up a holdall and firing up the online check-in app. Whether he is still there or not, Leicester will surely already be down by 3 May when they face Southampton at home – a chance for both sets of owners to stand up and take accountability for dreadful seasons, which Football Daily is confident they’ll take. Still, with the gulf between England’s top two divisions only growing, don’t be surprised if both teams are cruising back towards the Premier League in a year’s time, having failed to learn a single thing. LIVE ON BIG WEBSITE Simon Burnton will helm our piping hot coverage of Belgium 1-2 England in the Women’s Nations League, with kick-off from 7.30pm (all times BST). Oh, and you might have heard that there’s also Bigger Cup tonight. Rob Smyth is in position for Arsenal 1-3 Real Madrid, while Niall McVeigh will take on Bayern 1-1 Internazionale, with both kick-offs at 8pm. QUOTE OF THE DAY I was coaching from 18-19 years old and nobody knew. I did things so under the radar that people at the FA didn’t even know” – Jo Potter, Rangers Women’s head coach and former England international, talks to Sophie Downey about her own development, the need for Scotland to do well and winning silverware in the latest edition of Moving the Goalposts. FOOTBALL DAILY LETTERS Regarding yesterday’s news that Brazilian authorities now deem standing on a ball to be a yellow card offence, it just shows how ahead of the game Uefa were. Wayne Rooney famously got a red card for this in 2006. But then he did stand on two of them at once” – Derek McGee. I was reading the Leicester v Newcastle live blog when I thought of a joke. May I test it with your readers? I figure they, I mean we, are well used to dodgy attempts at comedy. The Newcastle and Leicester managers walk into a bar, leaving the door open behind them. The bartender looks up and says ‘Howe, Ruud!’” – Peter Oh. Martin Ødegaard needs to be aware of an imposter on the Arsenal bench who sounds a bit like him (yesterday’s Football Daily). I had to press and hold the O on my iPhone to get that special Norwegian Ø you know” – Brian Wealthall (and 1,056 others). Send letters to the.boss@theguardian.com. Today’s letter o’ the day winner is … Peter Oh, who wins a copy of Groundhopper, by Pitch Publishing. Visit their bookshop here. Terms and conditions for our competitions can be viewed here. RECOMMENDED LOOKING Fan protests, football influencers and topless Glazers: yep, it’s David Squires. This is an extract from our daily football email … Football Daily. To get the full version, just visit this page and follow the instructions."
        },
        "tags": [
            {
                "id": "football/leicestercity",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Leicester City",
                "webUrl": "https://www.theguardian.com/football/leicestercity",
                "apiUrl": "https://content.guardianapis.com/football/leicestercity",
                "references": [],
            },
            {
                "id": "football/football",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Football",
                "webUrl": "https://www.theguardian.com/football/football",
                "apiUrl": "https://content.guardianapis.com/football/football",
                "references": [],
            },
            {
                "id": "sport/sport",
                "type": "keyword",
                "sectionId": "sport",
                "sectionName": "Sport",
                "webTitle": "Sport",
                "webUrl": "https://www.theguardian.com/sport/sport",
                "apiUrl": "https://content.guardianapis.com/sport/sport",
                "references": [],
            },
            {
                "id": "football/premierleague",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Premier League",
                "webUrl": "https://www.theguardian.com/football/premierleague",
                "apiUrl": "https://content.guardianapis.com/football/premierleague",
                "references": [],
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/sport",
        "pillarName": "Sport",
    },
    {
        "id": "football/2025/apr/08/a-kevin-de-bruyne-mls-move-could-be-with-messi-in-miami-heres-how",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2025-04-08T14:52:09Z",
        "webTitle": "Kevin De Bruyne could move to Messi’s Inter Miami. Here’s how",
        "webUrl": "https://www.theguardian.com/football/2025/apr/08/a-kevin-de-bruyne-mls-move-could-be-with-messi-in-miami-heres-how",
        "apiUrl": "https://content.guardianapis.com/football/2025/apr/08/a-kevin-de-bruyne-mls-move-could-be-with-messi-in-miami-heres-how",
        "fields": {
            "bodyText": "If Kevin De Bruyne decides to come to Major League Soccer for his next professional stop, the destination could very well be with Lionel Messi at Inter Miami. The Athletic and ESPN each reported on Monday that the south Florida club have acquired the Belgian star’s discovery rights, giving them the right of first refusal to negotiate a contract with De Bruyne should he decide to move to the league after he leaves Manchester City. Inter Miami declined to comment on the reports. The MLS discovery process allows each MLS team to name up to five players that they have the initial right to negotiate with for potential signings. De Bruyne’s discovery rights were initially held by expansion side San Diego FC, but the club removed him from their list earlier this year, according to GiveMeSport, after determining that the player did not fit their plans. The remaining hurdle for any move, aside from the player’s wish to do so, is salary. De Bruyne reportedly earns around £20m ($25.5m) per year at Man City, a figure that would likely make him comfortably the highest-paid player in MLS, ahead of Messi’s $20m deal. Even if De Bruyne takes a large pay cut, MLS roster rules limit Miami’s flexibility somewhat. Currently, the maximum annual salary per player allowed under MLS rules is just over $740,000, but there are multiple ways players can be paid more, sometimes significantly so. The most famous of these is the designated player (DP) rule. Each MLS team is allowed to sign up to three designated players, each of which can be paid any amount by the club while only counting against the club’s cap at the maximum salary (Messi, for example, only hits Miami’s cap at that $740,000 figure, with the club itself paying out the difference). De Bruyne’s wage demands would surely pass the DP threshhold, but Miami are presently using their three DP spots on Messi, Jordi Alba and Sergio Busquets. That probably closes the door to De Bruyne signing as a DP this summer, but it’s important to note that all three of Miami’s current DPs are on contracts that end after the 2025 season. A more likely route would be to add De Bruyne this summer using mechanisms known as targeted allocation money and general allocation money (TAM and GAM). While the uses for each vary somewhat, both mechanisms essentially give teams extra space on their salary budget by allowing them to “buy down” a player’s cap hit. Miami could use GAM and/or TAM to reduce De Bruyne’s salary hit to below the maximum budget charge, but it’s unknown exactly how much they’ll have to work with. The club is now listed as having about $3.1 in GAM available. Their current TAM holdings are unknown, but each MLS team was given $2.2m in TAM at the start of 2025 and Inter Miami currently lists six players (including Luis Suárez) whose budget charges have been bought down using the mechanism, so it’s unlikely to be much. Still, there is some precedent for star players joining MLS teams in the summer on non-DP deals, only to be made DPs later on. Zlatan Ibrahimović is perhaps the most famous of these, with the Swedish striker joining LA Galaxy on a TAM deal midway through the 2018 season, only to be then handed a new DP-level contract before the 2019 campaign. Inter Miami’s Jordi Alba, too, joined the club on a TAM-level one and a half-year deal in the same 2023 summer window as Messi. That deal was later extended and, in the process, made Alba a DP."
        },
        "tags": [
            {
                "id": "football/kevin-de-bruyne",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Kevin De Bruyne",
                "webUrl": "https://www.theguardian.com/football/kevin-de-bruyne",
                "apiUrl": "https://content.guardianapis.com/football/kevin-de-bruyne",
                "references": [],
            },
            {
                "id": "football/mls",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "MLS",
                "webUrl": "https://www.theguardian.com/football/mls",
                "apiUrl": "https://content.guardianapis.com/football/mls",
                "references": [],
            },
            {
                "id": "football/manchestercity",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Manchester City",
                "webUrl": "https://www.theguardian.com/football/manchestercity",
                "apiUrl": "https://content.guardianapis.com/football/manchestercity",
                "references": [],
                "description": "Read the latest Manchester City news, transfer rumours, match reports, fixtures and live scores from the Guardian",
            },
            {
                "id": "football/belgium",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Belgium",
                "webUrl": "https://www.theguardian.com/football/belgium",
                "apiUrl": "https://content.guardianapis.com/football/belgium",
                "references": [],
            },
            {
                "id": "football/football",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Football",
                "webUrl": "https://www.theguardian.com/football/football",
                "apiUrl": "https://content.guardianapis.com/football/football",
                "references": [],
            },
            {
                "id": "sport/sport",
                "type": "keyword",
                "sectionId": "sport",
                "sectionName": "Sport",
                "webTitle": "Sport",
                "webUrl": "https://www.theguardian.com/sport/sport",
                "apiUrl": "https://content.guardianapis.com/sport/sport",
                "references": [],
            },
            {
                "id": "sport/us-sport",
                "type": "keyword",
                "sectionId": "sport",
                "sectionName": "Sport",
                "webTitle": "US sports",
                "webUrl": "https://www.theguardian.com/sport/us-sport",
                "apiUrl": "https://content.guardianapis.com/sport/us-sport",
                "references": [],
            },
            {
                "id": "football/premierleague",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Premier League",
                "webUrl": "https://www.theguardian.com/football/premierleague",
                "apiUrl": "https://content.guardianapis.com/football/premierleague",
                "references": [],
            },
            {
                "id": "football/inter-miami",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Inter Miami",
                "webUrl": "https://www.theguardian.com/football/inter-miami",
                "apiUrl": "https://content.guardianapis.com/football/inter-miami",
                "references": [],
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/sport",
        "pillarName": "Sport",
    },
    {
        "id": "us-news/2025/apr/08/boston-nurses-brain-tumors",
        "type": "article",
        "sectionId": "us-news",
        "sectionName": "US news",
        "webPublicationDate": "2025-04-08T14:06:24Z",
        "webTitle": "Five nurses from same unit in Boston hospital diagnosed with brain tumors",
        "webUrl": "https://www.theguardian.com/us-news/2025/apr/08/boston-nurses-brain-tumors",
        "apiUrl": "https://content.guardianapis.com/us-news/2025/apr/08/boston-nurses-brain-tumors",
        "fields": {
            "bodyText": "Five nurses working in the same unit at a Boston-area hospital have been diagnosed with non-cancerous brain tumors, prompting them and their labor union to search for answers while the medical facility contends it has ruled out an environmental risk for workers there. According to a statement that Mass General Brigham’s Newton-Wellesley hospital provided to NBC10 Boston, the five nurses either work or have previously worked in the facility’s fifth-floor maternity unit. The hospital said it interviewed 11 staff members who have worked at some point on that floor as part of an investigation into the nurses and the tumors. Of them, five were diagnosed with brain tumors, all of which were benign growths, while the other six were found to have other health concerns. The hospital said it worked with internal and government occupational safety offices – and that it consulted external environmental experts. Officials at the Newton-Wellesley hospital said they gave every staff member who came forward the opportunity to be interviewed by the occupational health and safety team to evaluate their diagnoses in relation to their individual medical history and risk factors. Environmental assessments of the area which began in December “found no environmental risks which could be linked to the development of a brain tumor”, the hospital added. In a memo, the hospital outlined that it tested the facility’s water, measured radiation levels, assessed air quality and conducted other relevant evaluations. Newton-Wellesley officials said they presented their findings to “relevant stakeholder groups, including the staff in the unit” and the union representing them, the Massachusetts Nurses Association. And it said the hospital had held forums to meet with clinical and occupational health leaders to address their questions. Additionally, the hospital said that it was providing the union with the test results from the investigation – including those of several external environmental firms. Citing its findings, the hospital added: “We can confidently reassure our dedicated team members … and all our patients that there is no environmental risk at our facility. “As always, the health and wellbeing of our staff, clinicians, and patients is our absolute top priority.” However, the Massachusetts Nurses Association told NBC10 Boston that it was continuing to investigate the issue. The union has reported receiving more than 300 survey responses, emails and telephone calls from current nurses, other professionals at the hospital, and former employees. “It will take several weeks to sort through the information received, vet it, and obtain follow-up, including medical records, if respondents are willing to provide them,” the union said. The union also maintained that “the hospital only spoke to a small number of nurses” and that the hospital’s “environmental testing was not comprehensive”. It added: “The hospital cannot make this issue go away by attempting to provide a predetermined conclusion.” According to NBC Boston, officials from Newton-Wellesley hospital are set to discuss the matter in an upcoming town hall meeting."
        },
        "tags": [
            {
                "id": "us-news/boston",
                "type": "keyword",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webTitle": "Boston",
                "webUrl": "https://www.theguardian.com/us-news/boston",
                "apiUrl": "https://content.guardianapis.com/us-news/boston",
                "references": [],
            },
            {
                "id": "us-news/healthcare",
                "type": "keyword",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webTitle": "US healthcare",
                "webUrl": "https://www.theguardian.com/us-news/healthcare",
                "apiUrl": "https://content.guardianapis.com/us-news/healthcare",
                "references": [],
            },
            {
                "id": "us-news/massachusetts",
                "type": "keyword",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webTitle": "Massachusetts",
                "webUrl": "https://www.theguardian.com/us-news/massachusetts",
                "apiUrl": "https://content.guardianapis.com/us-news/massachusetts",
                "references": [],
            },
            {
                "id": "society/hospitals",
                "type": "keyword",
                "sectionId": "society",
                "sectionName": "Society",
                "webTitle": "Hospitals",
                "webUrl": "https://www.theguardian.com/society/hospitals",
                "apiUrl": "https://content.guardianapis.com/society/hospitals",
                "references": [],
                "description": "The latest news and comment on hospitals",
            },
            {
                "id": "us-news/us-news",
                "type": "keyword",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webTitle": "US news",
                "webUrl": "https://www.theguardian.com/us-news/us-news",
                "apiUrl": "https://content.guardianapis.com/us-news/us-news",
                "references": [],
            },
            {
                "id": "society/health",
                "type": "keyword",
                "sectionId": "society",
                "sectionName": "Society",
                "webTitle": "Health",
                "webUrl": "https://www.theguardian.com/society/health",
                "apiUrl": "https://content.guardianapis.com/society/health",
                "references": [],
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/news",
        "pillarName": "News",
    },
    {
        "id": "football/2025/apr/08/george-robledo-newcastle-great-scoring-record-overseas",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2025-04-08T12:00:13Z",
        "webTitle": "George Robledo: Newcastle great with a record beyond Salah and Henry",
        "webUrl": "https://www.theguardian.com/football/2025/apr/08/george-robledo-newcastle-great-scoring-record-overseas",
        "apiUrl": "https://content.guardianapis.com/football/2025/apr/08/george-robledo-newcastle-great-scoring-record-overseas",
        "fields": {
            "bodyText": "It was a question that had everyone in the room stumped, almost to the point of silence. “Who holds the record for the most league goals scored by an overseas player in the top flight of English football in a single season?” I felt as if I should know the answer, having written about sport for the vast majority of my adult life. But I didn’t. There I was, appearing as a guest at the Brighton branch of Sporting Memories, a UK charity which encourages older people to meet and reminisce through talking about sport, and I’d seemingly been exposed as a total fraud. A few educated guesses had been made initially by the 20 or so members who’d gathered to hear me talk about my latest book before getting down to the far more serious business of their weekly Monday morning quiz. Thierry Henry? Cristiano Ronaldo? What about Dennis Bergkamp? Or Luis Suárez? One by one our quizmaster, the former England rugby union international, cricketer and BBC broadcaster Alastair Hignell, batted away each incorrect answer including my own shot at restoring some professional pride (Mohamed Salah, just in case you were wondering). Gradually, the suggestions became little more than shots in the dark. Robin van Persie? Gianfranco Zola? Not Ricky Villa, surely? Robert Pires? Until, in David Ginola’s wake, the well of potential candidates ran dry and an air of befuddlement fell across the group. Maybe it was the presence of the former Wales and Newcastle United goalkeeper Dave Hollins in the room that did it, but out of the blue someone came up with a name, the correct name at that – George Robledo. George Robledo! Yes, YES! … and it all came flooding back. Some 20 or so years previously, I’d covered a Newcastle United game at St James’ Park during the managerial reign of Bobby Robson, often cited as one of the nicest guys to walk the earth, let alone work in football. The post-match press conference had ended but Robson continued talking to some of us hacks who weren’t on a deadline about his heroes, the ones he’d watched playing for Newcastle while growing up in north-east England in the years immediately after the second world war. He mentioned Jackie Milburn – I knew about him. He mentioned Joe Harvey – I knew about him, too. But then Robson said another name which meant absolutely nothing to me. That name was George Robledo. Clocking a couple of blank expressions in our midst, Robson gave us George Robledo in a nutshell. I wasn’t taking notes, just listening intently, but this much I do recall – he’d come as a boy from Chile to Yorkshire, worked as a miner before becoming a professional footballer, and scored lots of goals for several clubs (including Newcastle’s winner against Arsenal in the 1952 FA Cup final, a picture of which painted by the 11-year-old John Lennon would later appear on the cover of the former Beatle’s 1974 solo album, Walls and Bridges). I also recollect Robson saying he saw plenty of George Robledo in Alan Shearer. Praise indeed, as anyone who remembers Shearer in his pomp would acknowledge. On the long drive back to my home in Cardiff, I thought a lot about George. Here was someone who scored 33 league goals for Newcastle in the First Division (or the Premier League in today’s money) during the 1951-52 season. No overseas-registered, foreign-born player had reached that number before, and no overseas-registered, foreign-born player has reached that number since (although Mohamed Salah is doing his level best to change this). At the time of my visit to Brighton (January 2023) Manchester City’s Norway international Erling Haaland was on course to break George’s record, a feat Planet Football has since decreed he achieved. But then, as one extremely clued-up member of that Sporting Memories group had pointed out, Haaland was born in Leeds. As in Leeds, England, where his father once played football. Going by the rules of geography George is, as I write, still the record holder. Splitting hairs? Maybe, maybe not. It all depends how accurate, or perhaps pedantic, you want to be. Either way, there were two undeniable truths about George Robledo. One, he had clearly been a phenomenal football player. And two, his remarkable achievements seemed to have been almost completely forgotten in his adopted country. On reaching Cardiff, I fired up my laptop to see whether a book had been written about George, partly because I wanted to read one, and partly (the greater part, admittedly) because I felt a sudden calling and fancied having a go myself. No such book existed. So I went for it, blind at that stage to what exactly I was taking on but determined to unearth the treasure that was, and remains, George Robledo. The catch about unearthing something long hidden is that besides all the “wonderful things”, as Howard Carter described the contents of Tutankhamun’s tomb on first sight, you can also chance upon plenty of heartache. And so it would prove with George. Aged six, he and his two younger brothers had been abandoned by their father on the very day the Robledo family was due to set sail from Chile to start a new life in England. One of those brothers, Ted, who would also become a professional footballer and sign for Newcastle, was later murdered in mysterious circumstances in the Middle East, his body supposedly thrown into the Gulf from an oil tanker. There was also the brother George never knew, the result of a clandestine meeting in Hull between his mother and the father who, years before, had walked out of his life at the drop of a hat in Chile. The baby was given up by his mother and raised in a children’s home. And yet, as befits someone who grew up surrounded by poverty and worked in a Yorkshire mine as a Bevin Boy during the second world war, George never regarded himself as a victim. As a young man his creative feats at inside forward for Barnsley turned him into a local hero and secured a transfer to Newcastle in 1949. The following year he became the first Football League player from outside the British Isles to face England in an official international, acting as Chile’s talisman when the nations met at the 1950 World Cup in Brazil. In 1951 George was the first South American to play in an FA Cup final as Newcastle defeated Blackpool 2-0 at Wembley. Twelve months later he scored the only goal as the Magpies saw off Arsenal to retain the trophy. In 1953, driven by a desire to travel and with the maximum wage still in force in English football, George returned to Chile to sign for Colo-Colo, the country’s most successful club, more than doubling his weekly income. To quote George’s only child, Elizabeth Robledo: “That’s pretty good going for someone born in the Atacama desert, probably the driest, most inhospitable place on Earth, and I don’t think my dad ever lost sight of that.” Postcards From Santiago – The George Robledo Story by Spencer Vignes is published by Biteback (£20). To support the Guardian and the Observer buy a copy at guardianbookshop.com. Delivery charges may apply."
        },
        "tags": [
            {
                "id": "football/football",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Football",
                "webUrl": "https://www.theguardian.com/football/football",
                "apiUrl": "https://content.guardianapis.com/football/football",
                "references": [],
            },
            {
                "id": "sport/sport",
                "type": "keyword",
                "sectionId": "sport",
                "sectionName": "Sport",
                "webTitle": "Sport",
                "webUrl": "https://www.theguardian.com/sport/sport",
                "apiUrl": "https://content.guardianapis.com/sport/sport",
                "references": [],
            },
            {
                "id": "football/newcastleunited",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Newcastle United",
                "webUrl": "https://www.theguardian.com/football/newcastleunited",
                "apiUrl": "https://content.guardianapis.com/football/newcastleunited",
                "references": [],
            },
            {
                "id": "football/barnsley",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Barnsley",
                "webUrl": "https://www.theguardian.com/football/barnsley",
                "apiUrl": "https://content.guardianapis.com/football/barnsley",
                "references": [],
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/sport",
        "pillarName": "Sport",
    },
    {
        "id": "thefilter/2024/nov/16/best-christmas-gifts-kids-teenagers-lego-fashion-beauty-adidas-trainers",
        "type": "article",
        "sectionId": "thefilter",
        "sectionName": "The Filter",
        "webPublicationDate": "2025-04-08T09:14:31Z",
        "webTitle": "The best gifts for teens: 45 present ideas – chosen by teenagers themselves",
        "webUrl": "https://www.theguardian.com/thefilter/2024/nov/16/best-christmas-gifts-kids-teenagers-lego-fashion-beauty-adidas-trainers",
        "apiUrl": "https://content.guardianapis.com/thefilter/2024/nov/16/best-christmas-gifts-kids-teenagers-lego-fashion-beauty-adidas-trainers",
        "fields": {
            "bodyText": "When it comes to shopping for the teenagers in your life, it helps to consult an expert. So who better to advise than teenagers themselves? We asked students in years 10 and 11 at the Maelor School in Wrexham, Wales; year 9 at Nunnery Wood High School in Worcester; and sixth formers at Derby College in Derbyshire to share their (reasonable) wishlists. Here are 40-plus gift suggestions (or should that be requests?) from the people best qualified to tell you what teens really want. *** The best gifts for teens *** Cold cases The Naturals Complete Box Set by Jennifer Lynn Barnes £35.96 at the Guardian Bookshop £22.99 at Amazon I first heard about these books through TikTok and I’ve been wanting to read them for a while. They’ve really captured my attention with the blurb and the covers. Heather, 17 *** Cuddle up Kids’ faux fur blanket £24 at John Lewis £11.97 at Amazon They’re very pretty and comforting. My friend has one in her bedroom, and when we watched a scary film we hid under it! Ellie, 13 *** Get a grip Gain the Edge grip socks £9.99 at Gain the Edge £16.99 at Amazon I’d like these grip socks because I play rugby and get blisters on my feet when they rub in my boots. James, 15 *** Cool-cat trainers Adidas Originals Campus 00s skate shoes £90 at Asos £90 at Adidas I love leopard-print stuff – these trainers would look amazing with most of my outfits. Lexi, 14 *** Rock out Midas by Wunderhorse 12in album £29.99 at HMV £20.54 at Rarewaves It has a good sound and would be better on vinyl. Libby, 18 *** Quack quack Jellycat Yummy Duckling plushie £18 at Happy Returns I would really like a Jellycat Yummy Duckling soft plushie. It’s such a cute and adorable toy and probably the only toy brand acceptable for teenagers. I already have three Jellycats at home and wish to grow my collection. Annie, 14 *** Say cheese Fujifilm Instax Mini 12 instant camera From £69 at John Lewis From £67 at Amazon A Fuji Instax Mini camera, to take pics with my friends. Seren, 14 *** Arty types Ugee drawing tablet S640 £38 at Ugee £27.99 at Amazon I want a drawing tablet because I saw someone using one and it looked like a handy tool to help me get good at drawing. Joe, 15 *** Game on EA Sports FC25 – FC points 1,050 £8.99 at Xbox £8.99 at PlayStation The latest Fifa is out and my team is not very good. With more points, I could buy a player pack that would help with my team. Josef, 15 *** Poster boys Mainoo, Garnacho, Højlund magnetic metal poster From £39 at Displate I have supported Manchester United since I was little and they are some of my favourite players. I heard about these metal posters on TikTok and think a magnetic poster would look nicer than a normal one. Josef, 15 *** Smart kit Wrexham 24/25 away shirt From £20 at Wrexham AFC I would like the Wrexham black shirt. It looks good and it would be nice to go to the matches in the away shirt. Elliot, 14 *** Money, money, money It will help me pay for wants and needs. Ellie, 19 *** Heaven scent Ted Baker Rose and Orchid body spray £5.33 at Boots I tested it out and it smelled amazing. Nuha, 17 *** Cool buds Beats Solo buds £79.99 at Beats by Dre £79 at Amazon I’ve seen Beats headphones on TikTok and they have a good vibe. Libby, 18 *** Happy feet Ugg women’s classic ultra mini boot £145 at Ugg £145 at Office They look really nice, come in different colours and go with any outfit. Everyone was wearing them last winter and I would like a pair. And I’m always cold! Lucy, 13 *** Swiftie stickers Taylor Swift-inspired stickers, 50-pack, £3.99 at Amazon They’re the perfect decoration. I can use them on my guitar and record player. Charlotte, 14 For more Taylor Swift-inspired gifts, see our Swifties gift guide *** Pretty in pink Ariana pink taffeta blouse £49 at Damson Madder £95 at Revolve I need new clothes and want something that looks nice. Poppy, 13 *** Vincent van Lego The Starry Night Lego set £149.99 at Lego £144.99 at John Lewis Lego is one of my favourite things to create, and I love art and the Starry Night painting. I heard about this piece on TikTok while scrolling one night and now I have my heart set on it. Lois, 15 *** All heart Aqua opal heart necklace From £49 at Laura Gravestock My clothing style has changed and I would like jewellery that matches my clothes now. Paige, 17 *** Customised Converse Custom Chuck Taylor All Star By You £80 at Converse I would really love a pair of custom Converse, navy on one side and black on the other. I’ve wanted these ever since my cousin got hers a couple of years ago. I already have two pairs of Converse – one white, and one with a pink bottom, which I love – but I would also like a darker-coloured pair for colder, rainier seasons, so they don’t get as dirty. Maggie, 13 *** Super-cutesy animals Aphmau mystery MeeMeows plush £11.99 at Smyths I came across this as the producer is a popular Minecraft YouTuber that I follow. The colours and different characters make them appealing. I would like this item as I collect them and I’m trying to complete the sets. Chloe, 14 *** Get that healthy glow Glow Hub Mini Purify and Brighten Super Serum £8 for 15ml at Beauty Bay £13 for 30ml at Look Fantastic Starface Hydro-Stars + Big Yellow kit £11.95 at Beauty Bay £6.74 at Amazon I’d love some new products to improve my skin and make it glow. Audrey, 18 *** Chic crew Polo Ralph Lauren cable knit jumper £189 at Ralph Lauren £189 at Next They’re really nice, good-quality jumpers. I’ve seen people wearing them and you can wear them all year round. Lucy, 13 *** Denim dream Embellished Miss Me jeans £70.06 at Miss Me I like Miss Me low-rise jeans because they’re cute. I came across them on Vinted. Kim, 14 *** Pyjama drama Victoria’s Secret pretty blossom short pyjama set £55 at Victoria’s Secret Stripe &amp; Stare summer garden short pyjama set £85 at Stripe &amp; Stare I want new pyjamas so when I go to friends’ houses for sleepovers I have a nice pair to bring. Isabella, 13 *** Pretty pumps Bloch demi-pointe shoes £52 at Bloch World Freed classic demi-pointe shoe From £47.50 at Move Dance My current pair are nearly a year old and painful to wear. I worked hard to be able to get them, but I want a new pair. Scarlet, 13 *** Hair tamers Good Squish Cowboy Spaghetti scrunchie £30 at Good Squish Nobody’s Child floral and leopard-print scrunchie two-pack £15 at Nobody’s Child I would like something to go with my outfits. Polly, 13 *** True blue 1988-90 Everton Umbro track jacket From £98 at Vintage Football Shirts I’ve been a proud Blue all my life and I’ll take any opportunity to get the badge in. I also really like vintage jackets from the 90s and vintage football shirts, so this would be a great addition to my collection. Tomos, 14 *** Nail it Palette Royal Peacock nail paint £8 at Palette £8 at Amazon Nail polish in nice colours, because you can do cool designs. Esme, 13 *** Marine dream Pandora pink sea turtle dangle charm £60 at Pandora I would like a new Pandora charm to add to my bracelet because I’ve only got a few. I like the pink turtle charm. Lily, 14 *** Woolly thinking Super duper sweater beginner knitting kit From £59.25 at Wool and the Gang Lucinda jumper knitting kit From £59.99 at Wool Couture Company I love to crochet, so more yarn would be a welcome addition to my collection. I usually see ideas on Pinterest, then shop and make them accordingly. Heather, 17 For more needlecraft gift ideas, see our guide to the best beginner crochet kit *** Smell like a god Versace Eros Flame eau de parfum £95 at Harvey Nichols £95 at Boots It’s good to smell nice and this seems like a nice fragrance. James, 14 *** Get active I’m starting to go to the gym and would like a membership for a year. Sebastian, 14 *** Fine fragrance Lynx blue lavender body spray £5 at Tesco £5 at Superdrug I want the blue lavender Lynx because it’s the new one and I’ve never tried it. Noah, 14 *** A ‘get out of homework free’ voucher … so I can have more free time at home. Evan, 13 *** Here come the Gazelles … Adidas Gazelle trainers £85 at Adidas £85 at JD Sports I want the navy Adidas Gazelles. They’re in fashion. Ashton, 14 *** It’s mine! Personalised Dairy Milk 360g From £2.75 at Cadbury Personalised Tony’s Chocolonely 180g From £7.13 at Tony’s Chocolonely I would like lots of sweets and chocolate. Lukas, 14 For more, check out our guide to personalised gifts *** Personal touch Personalised phone case £14 at Not Another Bill *** Scribble it down Hardback notebook £22 at Papier With thanks to the Guardian Foundation • This article was originally published on 16 November 2024. Reviews published in the Filter may be periodically updated to reflect new products and at the editor’s discretion. The date of an article’s most recent update can be found in the timestamp at the top of the page. This piece was updated on 8 April 2025; new recommendations were added and prices were updated throughout."
        },
        "tags": [
            {
                "id": "lifeandstyle/family",
                "type": "keyword",
                "sectionId": "lifeandstyle",
                "sectionName": "Life and style",
                "webTitle": "Family",
                "webUrl": "https://www.theguardian.com/lifeandstyle/family",
                "apiUrl": "https://content.guardianapis.com/lifeandstyle/family",
                "references": [],
            },
            {
                "id": "lifeandstyle/lifeandstyle",
                "type": "keyword",
                "sectionId": "lifeandstyle",
                "sectionName": "Life and style",
                "webTitle": "Life and style",
                "webUrl": "https://www.theguardian.com/lifeandstyle/lifeandstyle",
                "apiUrl": "https://content.guardianapis.com/lifeandstyle/lifeandstyle",
                "references": [],
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/lifestyle",
        "pillarName": "Lifestyle",
    },
    {
        "id": "sport/2025/apr/08/why-john-amaechi-backs-change-british-basketball",
        "type": "article",
        "sectionId": "sport",
        "sectionName": "Sport",
        "webPublicationDate": "2025-04-08T09:00:38Z",
        "webTitle": " ‘Players want a different path’: why John Amaechi backs change in British basketball",
        "webUrl": "https://www.theguardian.com/sport/2025/apr/08/why-john-amaechi-backs-change-british-basketball",
        "apiUrl": "https://content.guardianapis.com/sport/2025/apr/08/why-john-amaechi-backs-change-british-basketball",
        "fields": {
            "bodyText": "Having played professional basketball in five countries, including spells at three NBA franchises, John Amaechi would appear better qualified than most to comment on the state of the sport in this country. So when he describes the nine Super League Basketball clubs as a “cartel” who churn out “sewage”, any interested parties are likely to listen – including the sports minister, Stephanie Peacock, who last week received a letter that included similar sentiments from Amaechi. Peacock has become involved, as the battle for control of British basketball has escalated to civil war. All nine SLB clubs have begun legal proceedings against the sport’s governing body, the British Basketball Federation, which last week signed a 15-year agreement with an American consortium called GBBL to operate a new men’s professional league from next year. As a result, the proposed new league has no clubs or venues, and the problems do not end there. UK Sport, the government body responsible for elite funding, has been asked to investigate whether the £4.75m given to basketball is secure given the allegations about the BBF’s tender process made by the clubs. In another extraordinary development, SLB referees are on strike after the Sheffield Sharks owner, Vaughn Millette, accused the experienced match official Eduard Udyanskyy of racism after his side lost against the Surrey 89ers last month. “There has been an ongoing issue of racism towards my coach [Atiba Lyons] from a certain referee for years now,” Millette wrote on X. An SLB game between the Bristol Flyers and the Caledonian Gladiators was postponed later that week as referees refused to officiate in an act of solidarity with Udyanskyy, and the SLB’s head of officiating, Richard Stokes, resigned in protest. A fortnight later, referees are being flown in from Canada to make sure the SLB can continue and in a final twist Millette, who as interim SLB chair was leading the clubs’ rebellion against the federation, has been forced to stand down despite a public apology and deleting his posts. An SLB investigation concluded there was “no evidence to support the claim of racism, corruption or cheating, in relation to Udyanskyy.” Given this mess it is hardly surprising Amaechi is scathing, and pins the blame firmly at the clubs. The 54-year-old is not involved in the league, but does have a good relationship with the BBF chair, Chris Grant, one of the driving forces behind it. “I feel the same way about the SLB clubs as I do about the water companies,” he says. “The natural resources are plentiful – there are so many talented youngsters in this country – but we end up with sewage. “The players want a different path and the leadership needs to change. In the corporate world, the market wouldn’t tolerate this level of failure. With the new proposal there’s potential for substantial investment in the sport. “It’s time for a change. I’m 54, and I’ve seen three generations of kids with more talent than me see it squandered through lack of opportunity and poor management. It would be nice if, before I die, one more kid from Manchester gets a chance to walk the parquet floors.” Amaechi is a longstanding critic of the SLB and its predecessor, the British Basketball League, which collapsed last year after the implosion of its financial backers, the one-time Everton buyers 777 Partners. Although not shy of giving an opinion, as a psychologist, professor of leadership at the University of Exeter and owner of a business transformation consultancy, he prefers to deal in forensic analysis. In a detailed study last month, which cited 10 previous research papers, Amaechi highlighted: short-term thinking and inconsistent leadership; chronic financial instability and poor commercial planning, weak brand positioning and ineffective marketing; neglect of grassroots development pathways; inadequate media presence and broadcasting strategy; lack of strategic government engagement; insufficient community-building and inclusion initiatives; failure to capitalise on cultural relevance. “The clubs are a cartel,” he says. “They are not a professional league. Most of the British players don’t get paid properly, their salaries are topped up by coaching. Spending hours each day coaching kids is not what a professional career should look like. “I’ve had BBL players live my house, as when they get knocked out of the competition they have nowhere to live. The number of BBL players I’ve bought food for because their contract doesn’t pay them enough ... “It’s a real shame that a cottage industry that has failed could stop the development of the game. In some quarters there’s the same level of nostalgia for the BBL as there is for Woolworths and it’s completely unearned.” The clubs have high-profile supporters of their own however, including the former sports minister Richard Caborn, who was instrumental in the development of the Olympic Legacy Park in Sheffield, which is home to the Sharks, Sheffield United Women and Sheffield Eagles rugby league club. Without getting into claims of illegality, Caborn questions the decision of the BBF to put the franchise to operate a new league out to tender in the first place, particularly as the SLB was given a licence to run it last summer. “The BBF have sold a franchise without clubs, facilities or players,” Caborn says. “They are selling a commodity that doesn’t exist. It would be like the FA telling the Premier League that they’ve sold the franchise to private investors, without the agreement of the clubs. How would that go down? I don’t know why they’re selling the franchise in the first place. The BBF gave the league a three-year licence last summer. They should be sitting down with the clubs to discuss how they can make this work. We could end up with two different leagues, which would be ludicrous.” Several sources have said, however, that the SLB licence contains a 12-month break clause, which it was always the intention to activate this summer, and that the three-year contract was only ever meant as an insurance policy in case the tender failed to attract credible bidders. Caborn also criticises elements of the BBF’s governance structure, with no club or SLB representation on its board. “British basketball is the only sport I can think of where the league and the biggest clubs aren’t represented on the governing body,” he says. “It’s madness.” BBF sources conceded this situation is suboptimal and will be addressed when the standoff regarding the new league is finally resolved, although the SLB also has governance issues. By retaining Millette as chair beyond 31 January – he stood down following the racism row at the end of March – the SLB was in breach of its licence that states that it requires independent leadership. As a result it could face a sanction from the BBF, although given the fires raging elsewhere that is the least of both side’s problems."
        },
        "tags": [
            {
                "id": "sport/gbbasketball",
                "type": "keyword",
                "sectionId": "sport",
                "sectionName": "Sport",
                "webTitle": "GB basketball",
                "webUrl": "https://www.theguardian.com/sport/gbbasketball",
                "apiUrl": "https://content.guardianapis.com/sport/gbbasketball",
                "references": [],
            },
            {
                "id": "sport/sport",
                "type": "keyword",
                "sectionId": "sport",
                "sectionName": "Sport",
                "webTitle": "Sport",
                "webUrl": "https://www.theguardian.com/sport/sport",
                "apiUrl": "https://content.guardianapis.com/sport/sport",
                "references": [],
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/sport",
        "pillarName": "Sport",
    },
    {
        "id": "football/2025/apr/07/jacob-murphys-lightning-double-helps-newcastle-blow-away-flimsy-leicester",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2025-04-07T22:16:20Z",
        "webTitle": "Van Nistelrooy in gloomy mood after Newcastle blow away flimsy Leicester",
        "webUrl": "https://www.theguardian.com/football/2025/apr/07/jacob-murphys-lightning-double-helps-newcastle-blow-away-flimsy-leicester",
        "apiUrl": "https://content.guardianapis.com/football/2025/apr/07/jacob-murphys-lightning-double-helps-newcastle-blow-away-flimsy-leicester",
        "fields": {
            "bodyText": "For Newcastle United, the comedown can wait. Eddie Howe’s side jumped to fifth in the Premier League to intensify their push for the Champions League after dismantling a sorry Leicester City, a club with a decision to make. Newcastle’s business was in effect complete after 34 minutes, courtesy of two goals by Jacob Murphy and one from Harvey Barnes. For Leicester, it is now a record eight home defeats in a row without scoring and 15 losses in their past 16 matches. Such damning statistics do not bode well for Ruud van Nistelrooy. Afterwards the noises from Van Nistelrooy were ominous. Asked whether he had the fight to continue, the Dutchman said: “It’s important to analyse this and sleep on it and recover.” Asked if he was committed to the job for the season, he replied: “The most important thing is the club and these players, that’s what I would say for now.” He repeated his previous answer when pushed whether he would carry on. As Newcastle’s supporters sang of Barcelona and Bayern Munich, Leicester fans faced up to the reality of trips to Preston and Portsmouth. “Say hello to Sunderland,” came the call. They have known for a while. Judging by the swathes of empty seats, many locals voted with their feet. Others have long since checked out. Leicester could be relegated as early as Easter Sunday. Until the second half fizzled out, it felt plausible that Newcastle could chalk up their biggest win, eclipsing an 8-0 victory over Sheffield United at Bramall Lane 18 months ago. It has been a fine few weeks for Howe and Newcastle, backing up their first major trophy in 70 years with successive league victories. “It was a big question mark: how do we react to the big high that we had?” Howe said. “The players have responded magnificently. It is a real tick in the box for our psychology.” The Newcastle manager said another reset is required, with three games in six days from Sunday, the first at home to Manchester United. “We need to keep that fine balance between confidence and needing to improve, because there are areas that haven’t been perfect. We need to look to continue to grow.” Undoubtedly the most enjoyable moment from a Leicester perspective was the arrival of the sought-after 15-year-old Jeremy Monga, who juggles school with first-team training. The youngster, wearing the No 93, entered for his debut in the 74th minute wearing a shirt without a sponsor owing to Leicester’s partnership with BC Game, a betting company. The other highlight was the opportunity to relive better days by singing Barnes’s name after he made it game, set and match. Leicester’s “Foxes never quit” motto was again under the microscope early on. Last Wednesday it was Jack Grealish after 70 seconds and this time Leicester’s defence held out a bit longer, with Murphy scoring his first goal with 115 seconds played. Jamie Vardy had prompted Nick Pope into action inside 11 seconds but from there it was a matter of how many Newcastle would finish up with. Newcastle mauled Leicester in midfield. The visitors profited to score their first; Bruno Guimarães was too strong for Wilfred Ndidi, Joelinton kept Boubakary Soumaré at arm’s length and Barnes spied Tino Livramento on the overlap. Livramento sent the ball towards the back post and Murphy side-footed in. For the 26th time in 31 league matches, Leicester had conceded the first goal. Leicester were so brittle it seemed Newcastle could score with every attack. The second goal, on 11 minutes, stemmed from Fabian Schär cracking the crossbar with a shot from inside his own half. Schär’s effort cannoned towards Murphy, who could afford a rusty first touch. The ball bobbled off his left knee but he soon found the net. “[It] only took me about seven touches to get it under and stick it in,” Murphy said. He could afford to smile. Leicester? Not so much. “You’re not fit to wear the shirt,” came the chant from the increasingly apathetic home support. Bilal El Khannouss tested Pope from a tight angle after a rare attack but Newcastle responded by adding a third. Barnes started and finished the move, dribbling across the pitch with conviction. Joelinton took over the baton and then chopped inside Wout Faes before forcing Mads Hermansen into a save. Barnes was alive in the box to dispatch the rebound. Leicester adopted damage-limitation mode at the Etihad Stadium but here Van Nistelrooy’s half-time changes at least appeared positive, with Facundo Buonanotte and Stephy Mavididi introduced. Newcastle grew a little lax – as if they had privately declared – but Leicester could not punish them. Faes flashed a header wide in stoppage time but it was another unhappy ending."
        },
        "tags": [
            {
                "id": "football/premierleague",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Premier League",
                "webUrl": "https://www.theguardian.com/football/premierleague",
                "apiUrl": "https://content.guardianapis.com/football/premierleague",
                "references": [],
            },
            {
                "id": "football/football",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Football",
                "webUrl": "https://www.theguardian.com/football/football",
                "apiUrl": "https://content.guardianapis.com/football/football",
                "references": [],
            },
            {
                "id": "football/leicestercity",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Leicester City",
                "webUrl": "https://www.theguardian.com/football/leicestercity",
                "apiUrl": "https://content.guardianapis.com/football/leicestercity",
                "references": [],
            },
            {
                "id": "football/newcastleunited",
                "type": "keyword",
                "sectionId": "football",
                "sectionName": "Football",
                "webTitle": "Newcastle United",
                "webUrl": "https://www.theguardian.com/football/newcastleunited",
                "apiUrl": "https://content.guardianapis.com/football/newcastleunited",
                "references": [],
            },
            {
                "id": "sport/sport",
                "type": "keyword",
                "sectionId": "sport",
                "sectionName": "Sport",
                "webTitle": "Sport",
                "webUrl": "https://www.theguardian.com/sport/sport",
                "apiUrl": "https://content.guardianapis.com/sport/sport",
                "references": [],
            },
        ],
        "isHosted": False,
        "pillarId": "pillar/sport",
        "pillarName": "Sport",
    },
]
